### ISSUE TITLE
Strip output from notebooks?

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/radar-cookbook#116]
I noticed that *some* (not all) notebooks in this repo are committed to main branch with output. Our [contributors guide](https://github.com/ProjectPythia/.github/blob/main/.github/CONTRIBUTING.md) suggests stripping output from notebooks since all output gets regenerated during the build process.

There is currently output in these files:
- `foundations/pyart-basics.ipynb`
- `foundations/pyart-corrections.ipynb`
- `foundations/pyart-gridding.ipynb`
- `foundations/interactive-radar-visualization.ipynb`
- `example-workflows/cacti-data-quality-example.ipynb`
- `example-workflows/echo_top_height.ipynb`
- `example-workflows/fastbarnes_interpolation_rhi.ipynb`
- `example-workflows/moore-oklahoma-tornado.ipynb`
- `example-workflows/tracer-example.ipynb`

In some cases it also looks like the output has been executed out of order.

@mgrover1 what's your opinion? Should we strip all output, or possibly check in new output from clean re-runs of each notebook?

**Comment by mgrover1** [comment]
Yeah - I think stripping out the output is a good plan. We might consider adding an action to auto-take care of this, otherwise I can take care of it

**Comment by brian-rose** [comment]
I can open a PR for this.

I would hesitate to build automation that removes content, since in some cases we have cookbooks with output included to get around build limitations.

**Comment by mgrover1** [comment]
Okay - sounds good!

**Comment by brian-rose** [comment]
Done in #118
